#!/bin/bash

set e

echo "Starting Cluster using minikube"

minikube start

echo "minikube cluster started"

echo "Checking Status"

kubectl cluster-info

echo "Retrieving all existing pods"

kubectl get pods --all-namespaces

echo "all events running"
