apiVersion: app/v1

kind: deployment

metadata: 
  name: drf-app-deployment
  labels:
    app: messaging_app

spec: 
  replicas: 3
  selector: 
    app: messaging_app
    version: blue
  template:
    metadata:
      labels:
        app: messaging_app
        version: blue
    spec:
      containers:
      - name: drf_app_container
        image: messaging_app:blue
        ports:
        - containerport: 8000
        envFrom:
        - secretRef:
            name:: mysql-secret