version: '3.8'

services:
  db:
    image: mysql:8.0.11
    restart: always
    env_file: .env
    environment:
      MYSQL_USER: ${MSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
  web:
    build: .
    command: python3 manage.py runserver
    volumes:
      - ".:/messaging_app"
    depends_on:
      - db
    env_file: .env
    environment:
      - MYSQL_DB=${MSQL_DB}
      - MYSQL_USER=${MSQL_USER}
      - MYSQL_PASSWORD=${MSQL_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
volumes:
    mysql_data: