pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
        DOCKER_IMAGE = 'skai001/messaging_app:latest'
    }

    stages {
        stage('checkout') {
            steps {
                git branch: 'main',
                credentialsId: 'github-credentials',
                url: 'https://github.com/TyroneKisienya/alx-backend-python.git'
            }
        }
        stage('Setup Python Environment') {
            steps {
                // shining panda in use
                script {
                    def python = tool name: 'Python 3', type: 'hudson.plugins.shiningpanda.tools.PythonInstallation'
                    env.PATH = '${python}/bin:${env.PATH}'
                }

                sh '''
                    python3 -m venv ${VENV_DIR}
                    source ${VENV_DIR}/bin/activate
                    pip3 install -r requirements.txt
                    '''
            }
        }
        stage('RUn Tests') {
            steps {
                sh '''
                source ${VENV_DIR}/bin/activate
                pytest --junitxml=report.xml
                '''
            }
        }
        stage('Publish Test Report') {
            steps {
                junit 'report.xml'
            }
        }
        stage('Manual Approval') {
            steps {
                input message: 'Do you want to continue to deploy?', ok: 'Yes, continue'
            }
        }
        stage('Build docker image') {
            steps {
                sh '
                docker build -t ${DOCKER_IMAGE}
                '
            }
        }
        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER'. passwordVariable: 'DOCKER_PASS')])
                sh '''
                echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                docker push ${DOCKER_IMAGE}
                '''
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished Cleaning up'
            sh 'deactivate || true' 
        }
    }
}