# Generated by Django 5.2.7 on 2025-10-27 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.conversation'),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='participants_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants_id',
            field=models.ManyToManyField(related_name='conversation', to=settings.AUTH_USER_MODEL),
        ),
    ]
